const urls = [
    "https://theauxevanston.com/",
    "https://theauxevanston.com/who-we-are/",
    "https://theauxevanston.com/what-we-do/",
    "https://theauxevanston.com/meet-our-tenants/",
    "https://theauxevanston.com/open-spaces/",
    "https://theauxevanston.com/milestones/",
    "https://theauxevanston.com/news/",
    "https://theauxevanston.com/contact/",
    "https://theauxevanston.com/invest-and-donate/",
    "https://theauxevanston.com/faqs/",
    "https://theauxevanston.com/meet-our-tenants/the-aux-wellness-collective/",
    "https://theauxevanston.com/meet-our-tenants/embrace-your-crown/",
    "https://theauxevanston.com/meet-our-tenants/the-laundry-cafe/",
    "https://theauxevanston.com/meet-our-tenants/our-unseen-roots-podcast-studio/",
    "https://theauxevanston.com/2023/06/03/tbf-diagnostic/",
    "https://www.facebook.com/theauxevanston/",
    "https://www.instagram.com/theauxevanston/",
];
export default urls;
