const urls = [
    "https://cne-official.webflow.io/about/history",
    "https://cne-official.webflow.io/about/impact",
    "https://cne-official.webflow.io/about/annual-reports",
    "https://cne-official.webflow.io/about/staff",
    "https://cne-official.webflow.io/about/board-policy-council",
    "https://cne-official.webflow.io/about/partners",
    "https://cne-official.webflow.io/about/employment-opportunities",
    "https://cne-official.webflow.io/for-families/programs-overview",
    "https://cne-official.webflow.io/for-families/head-start-early-head-start",
    "https://cne-official.webflow.io/for-families/programs-childcare-assistance-program-ccap",
    "https://cne-official.webflow.io/for-families/preschool-for-all",
    "https://cne-official.webflow.io/for-families/new-families",
    "https://cne-official.webflow.io/for-families/current-families",
    "https://cne-official.webflow.io/for-families/childcare-list",
    "https://cne-official.webflow.io/for-supporters/upcoming-events",
    "https://cne-official.webflow.io/for-supporters/supporters-list",
    "https://cne-official.webflow.io/for-educators/professional-development",
    "https://cne-official.webflow.io/for-supporters/news-events",
    "https://cne-official.webflow.io/contact",
];
export default urls;
